sudo: false
language: python
branches:
  except: [cookiecutter, refactor]
cache: pip
jobs:
  include:
  - {stage: check, python: '3.5', env: TOX_ENV=setup}
  - {stage: check, python: '3.5', env: TOX_ENV=safety}
  - {stage: check, python: '3.5', env: TOX_ENV=style}
  - {stage: check, python: '3.5', env: TOX_ENV=docs}
  - {stage: check, python: '3.5', env: TOX_ENV=spell}
  - {stage: check, python: '3.5', env: TOX_ENV=link}
  - {stage: test, after_success: 'tox -e codacy', python: '2.7', env: TOX_ENV=py27}
  - {stage: test, after_success: 'tox -e codacy', python: '3.4', env: TOX_ENV=py34}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-dev}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy}
  fast_finish: true
  allow_failures:
  - {stage: check, python: '3.5', env: TOX_ENV=style}
  - {stage: check, python: '3.5', env: TOX_ENV=spell}
  - {stage: check, python: '3.5', env: TOX_ENV=link}
  - {stage: test, python: 3.7-dev}
addons:
  apt:
    packages: [libenchant-dev]
install: [pip install -r requirements/ci.txt]
script: ['tox -e ${TOX_ENV}']
